export default {
  //BASE_URL: '/dataskai2',
  BASE_URL: '',
  API_URL: '/api',
  API_VERSION: '/v1',
  TASK_INFO_URL: '/tasks/{task_name}/info',
  TASK_CONFIG_URL: '/tasks/{task_name}/frontend_config',
  TASK_SUBMITS_URL: '/tasks/{task_name}/submits',
  TASK_SUBMITS_WITH_SUBMIT_ID_URL: '/tasks/{task_name}/submits/{submit_id}',
  COMPARISON_SUBMITS_URL: '/submits/comparison',
  COMPARISON_SUBMIT_FEATURES: '/submits/{submit_id}/features_info/comparison',
  PROJECT_TASKS_URL: '/project/tasks',
  PROJECT_CONFIG_URL: '/project/frontend_config',
  PROJECT_INFO_URL: '/project/info',
  TASK_FEATURES: '/tasks/{task_name}/features_info',
  SUBMIT_FEATURES: '/submits/{submit_id}/features_info',
  FETCH_DELAY: 500,
};
